/**
 * GENERATED by scripts/playbook/build-reply-templates.ts — DO NOT EDIT BY HAND.
 * Source: content/playbook/intents/*.md (## Email blocks). Regenerate after any
 * playbook edit: npx tsx scripts/playbook/build-reply-templates.ts
 */
import type { ReplyTemplate } from './reply-templates';

export const REPLY_TEMPLATES: readonly ReplyTemplate[] = [
  {
    "id": "quote-request",
    "label": "Quote",
    "subject": "Your Party On Delivery quote",
    "body": "Hi {{first_name}},\n\nHappy to price that out! Easiest way: I've put together a sample cart sized for your group — open it, edit anything, and it prices live: {{cart_url}}\n\nDelivery fee and order minimum depend on your delivery zip (checkout shows both exactly). Reply with your event date and headcount if it changes and I'll re-cut it for you personally.",
    "tokens": [
      "first_name",
      "cart_url"
    ]
  },
  {
    "id": "corporate-event-inquiry",
    "label": "Corporate",
    "subject": "Your corporate event with Party On Delivery",
    "body": "Hi {{first_name}},\n\nWe handle corporate events end-to-end: premium spirits and curated wine, full bar setups and TABC-certified bartenders if you want them, and an itemized quote/invoice your finance team can approve before anything's locked. Invoices can be paid by corporate card, ACH, or wire.\n\nReply with your date, headcount, venue, and rough budget per person, and I'll put together a proposal for you.",
    "tokens": [
      "first_name"
    ]
  },
  {
    "id": "bartender-services",
    "label": "Bartenders",
    "subject": "Bartender services for your event",
    "body": "Hi {{first_name}},\n\nYes! We provide TABC-certified, insured bartenders for weddings, corporate events, and private parties — plus custom cocktail menus and complete bar setups (glassware, ice, garnishes, mixers, tools). Packages start at $600, and the exact quote depends on your event.\n\nReply with your date, headcount, venue, and how many hours of service you need, and I'll put pricing together for you personally.",
    "tokens": [
      "first_name"
    ]
  },
  {
    "id": "partner-affiliate-inquiry",
    "label": "Partner",
    "subject": "Partnering with Party On Delivery",
    "body": "Hi {{first_name}},\n\nGreat to hear from you — I handle partnerships personally and I'd love to explore how we can work together. I'll follow up shortly with next steps. Appreciate you thinking of us!",
    "tokens": [
      "first_name"
    ]
  },
  {
    "id": "callback-request",
    "label": "Callback",
    "subject": "Your Party On Delivery callback",
    "body": "Hi {{first_name}},\n\nAbsolutely — got your message and I'll give you a call. If it's about an event happening today, reply \"TODAY\" and I'll bump you to the top. Otherwise I'll reach out during delivery hours (10 AM – 9 PM Mon–Sat).",
    "tokens": [
      "first_name"
    ]
  },
  {
    "id": "product-availability",
    "label": "Availability",
    "subject": "Finding what you need",
    "body": "Hi {{first_name}},\n\nEverything we can deliver is live at partyondelivery.com/products — search there for exactly what you're after. If it's not listed, reply with what you want and your event date; we can often source special requests with enough lead time.",
    "tokens": [
      "first_name"
    ]
  },
  {
    "id": "hours-availability",
    "label": "Hours",
    "subject": "Our delivery hours",
    "body": "Hi {{first_name}},\n\nOur delivery hours are 10 AM – 9 PM Monday through Saturday, and we can arrange early-morning or late-night deliveries with advance notice. We're closed Sundays for standard delivery, but special events on a Sunday can often be arranged — just reply with your date.\n\n(Holiday note: we're closed Thanksgiving Day and Christmas Day; every other holiday runs normal hours.)",
    "tokens": [
      "first_name"
    ]
  },
  {
    "id": "post-event-thanks",
    "label": "Thank you",
    "subject": "Thanks from Party On Delivery",
    "body": "Hi {{first_name}},\n\nThank you — that genuinely makes our day! To be honest, we're a growing business and reviews are super helpful. If you have 60 seconds, we'd love one: 123.partyondelivery.com/reviews\n\nHope to see y'all at the next one!",
    "tokens": [
      "first_name"
    ]
  }
];
