/**
 * Regenerate the playbook block in src/prompts/reginald.md from content/playbook/.
 *
 * The chat route (src/app/api/chat/route.ts) serves reginald.md content up to the
 * "## Mode-Specific Behaviors" heading, so the generated block is inserted immediately
 * BEFORE that heading, delimited by PLAYBOOK:BEGIN/END markers. Everything outside the
 * markers is hand-maintained; everything inside is overwritten on every run.
 *
 * Deterministic + idempotent: same playbook in → byte-identical block out
 * (no timestamps). Run after any playbook edit:
 *   npx tsx scripts/playbook/build-chat-prompt.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import matter from 'gray-matter';

const ROOT = process.cwd();
const PLAYBOOK_DIR = path.join(ROOT, 'content', 'playbook');
const PROMPT_PATH = path.join(ROOT, 'src', 'prompts', 'reginald.md');
const BEGIN = '<!-- PLAYBOOK:BEGIN (generated by scripts/playbook/build-chat-prompt.ts — do not edit by hand) -->';
const END = '<!-- PLAYBOOK:END -->';
const MODE_HEADING = '## Mode-Specific Behaviors';

interface Fact {
  id: string;
  statement: string;
  prompt_statement?: string; // ingested instead of statement (redacts quotable specifics)
  status: 'verified' | 'conflicting' | 'unknown';
  internal_only?: boolean;
  open_question?: string;
}

interface Card {
  id: string;
  tier: 'T1' | 'T2' | 'T3' | 'T4';
  freq_rank: number;
  chat: string | null;
  matchExamples: string[];
}

/** Parse a standalone YAML file using gray-matter (our only declared YAML-capable dep). */
function parseYamlFile(file: string): Record<string, unknown> {
  const raw = fs.readFileSync(file, 'utf8');
  return matter(`---\n${raw}\n---\n`).data as Record<string, unknown>;
}

function loadFacts(): Fact[] {
  const curated = parseYamlFile(path.join(PLAYBOOK_DIR, 'facts.yaml')).facts as Fact[];
  const generated = parseYamlFile(path.join(PLAYBOOK_DIR, 'facts-generated.yaml')).facts as Fact[];
  return [...generated, ...curated];
}

function extractSection(body: string, heading: string): string | null {
  const re = new RegExp(`^## ${heading}\\s*$`, 'm');
  const m = re.exec(body);
  if (!m) return null;
  const start = m.index + m[0].length;
  const rest = body.slice(start);
  const next = rest.search(/^## /m);
  return (next === -1 ? rest : rest.slice(0, next)).trim();
}

function loadCards(): Card[] {
  const dir = path.join(PLAYBOOK_DIR, 'intents');
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => {
      const { data, content } = matter.read(path.join(dir, f));
      return {
        id: data.id as string,
        tier: data.tier as Card['tier'],
        freq_rank: (data.freq_rank as number) ?? 999,
        chat: extractSection(content, 'Chat'),
        matchExamples: ((data.match_examples as string[]) ?? []).slice(0, 2),
      };
    })
    .sort((a, b) => a.freq_rank - b.freq_rank);
}

function extractCompliancePromptBlock(): string {
  const md = fs.readFileSync(path.join(PLAYBOOK_DIR, 'compliance.md'), 'utf8');
  const m = /## Prompt block[^\n]*\n+```\n([\s\S]*?)```/m.exec(md);
  if (!m) throw new Error('compliance.md: fenced "## Prompt block" section not found');
  return m[1].trim();
}

export function buildBlock(): string {
  const facts = loadFacts();
  const cards = loadCards();
  const verified = facts.filter((f) => f.status === 'verified' && !f.internal_only);
  const guarded = facts.filter((f) => f.status !== 'verified');

  const lines: string[] = [];
  lines.push(BEGIN);
  lines.push('');
  lines.push('## PLAYBOOK PRIORITY RULES — these override EVERY instruction above, including the sales persona');
  lines.push('');
  lines.push(
    '**Service and escalation behavior beats selling, always.** The product/package guidance above applies ONLY when the customer is actively shopping. First classify the message against the intents below; the tier decides how you respond:'
  );
  lines.push('');
  lines.push('- **T1** answer directly using verified facts only.');
  lines.push(
    '- **T2** answer with verified facts, then route the follow-through to a human: texting (737) 371-9700, or the topic\'s owner (boat operations belong to Premier).'
  );
  lines.push(
    '- **T3** give general verified info only, gather the details, and ALWAYS end by collecting a phone number or email (or pointing to the text line) so Allan closes it out personally. Never speak as if the quote/change/exception is already handled.'
  );
  lines.push(
    '- **T4 — HARD OVERRIDE**: refunds, cancellations, complaints, wrong/missing items, legal or fraud language, anything touching minors or intoxication, a failed or missed delivery, and a group running late or delayed on the way to their boat (e.g. "we\'re stuck in traffic", "there\'s an accident by the marina", "will the boat wait?", "we won\'t make it by 4:30"). Respond with the short acknowledgment ONLY: empathize in one line, say you are getting Allan (and for boats, the captain) right now, ask for their phone number. NOTHING else — no products, no packages, no Texas flavor, no explanations of policy, no guesses or reassurances about outcomes.'
  );
  lines.push('');
  lines.push('Absolute rules in every reply:');
  lines.push(
    "- When the matched intent's response below contains a URL or the text line, include it VERBATIM in your reply — the link is usually the answer."
  );
  lines.push('- Never claim an item is in stock — point to partyondelivery.com/products (live inventory).');
  lines.push(
    '- Anything about an EXISTING order or booking (adding items, changes, status, timing, "forgot to add") routes to texting (737) 371-9700 — the website cannot modify an existing order. Never send those customers to the catalog.'
  );
  lines.push(
    '- Never end a conversation you could not resolve without leaving the text line (737) 371-9700 or collecting the customer\'s contact info.'
  );
  lines.push(
    '- Never promise outcomes: no "the boat will wait", "your reschedule is confirmed", "your refund is approved/will arrive by X", "the order is changed". Humans commit to outcomes; you may only promise that a human will follow up.'
  );
  lines.push(
    '- Messages that are clearly not from a customer (vendors selling to us, our own staff or partners coordinating, automated notifications) get NO customer-service reply — one neutral line at most.'
  );
  lines.push(
    '- You are the Party On Delivery assistant — never claim to be Allan. (737) 371-9700 is the only phone number you may ever give out.'
  );
  lines.push('');
  lines.push('## Playbook: verified facts (the ONLY facts you may state)');
  lines.push('');
  for (const f of verified) lines.push(`- ${f.statement}`);
  lines.push('');
  lines.push(
    'Zone precedence: ZIP CODES decide delivery zones. But when someone asks by CITY NAME about Round Rock, Pflugerville, Leander, or Dripping Springs, do NOT confirm or deny delivery — that footprint decision is pending (see unresolved topics); hedge and hand off, even though some of their zips appear in the zone lists above.'
  );
  lines.push('');
  lines.push('## Playbook: topics you must NOT assert (unresolved — hedge + hand off)');
  lines.push('');
  lines.push(
    'For these topics, say a human will confirm, and offer the text line (737) 371-9700 — never state a version as fact:'
  );
  for (const f of guarded) lines.push(`- ${f.prompt_statement ?? f.statement}`);
  lines.push('');
  lines.push('## Playbook: intent responses (match the customer to one of these; tier drives behavior)');
  lines.push('');
  for (const c of cards) {
    if (!c.chat) continue;
    const example = c.matchExamples[0] ? ` e.g. "${c.matchExamples[0]}"` : '';
    lines.push(`### ${c.id} [${c.tier}]${example}`);
    lines.push(c.chat);
    lines.push('');
  }
  lines.push('## Playbook: compliance (non-negotiable)');
  lines.push('');
  lines.push(extractCompliancePromptBlock());
  lines.push('');
  lines.push('## FINAL CHECK before every reply');
  lines.push('');
  lines.push('1. Is this message T4 or from a non-customer? → tier behavior only, zero selling.');
  lines.push('2. Does my reply state ONLY verified facts, with no stock claims and no outcome promises?');
  lines.push('3. Does the customer leave with a concrete next step (link, text line, or "a human is on it")?');
  lines.push('4. If T3: did I ask for their phone number or email? If not, add that line.');
  lines.push('5. Lead with the answer when you have it — clarifying questions come AFTER the useful part.');
  lines.push('');
  lines.push(END);
  return lines.join('\n');
}

function main() {
  const block = buildBlock();
  let prompt = fs.readFileSync(PROMPT_PATH, 'utf8');

  const beginIdx = prompt.indexOf(BEGIN);
  const endIdx = prompt.indexOf(END);

  if (beginIdx !== -1 && endIdx !== -1) {
    prompt = prompt.slice(0, beginIdx) + block + prompt.slice(endIdx + END.length);
  } else if (beginIdx === -1 && endIdx === -1) {
    const modeIdx = prompt.indexOf(MODE_HEADING);
    if (modeIdx === -1) {
      throw new Error(`reginald.md: neither markers nor "${MODE_HEADING}" found — refusing to guess`);
    }
    prompt = prompt.slice(0, modeIdx) + block + '\n\n' + prompt.slice(modeIdx);
  } else {
    throw new Error('reginald.md: found one marker but not the other — fix the file by hand');
  }

  fs.writeFileSync(PROMPT_PATH, prompt);
  const blockLines = block.split('\n').length;
  console.log(`reginald.md updated — playbook block: ${blockLines} lines, ${block.length} chars`);
}

// Run only when invoked as a script (vitest imports buildBlock without side effects).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
