/**
 * Regenerate the playbook block in src/prompts/reginald.md from content/playbook/.
 *
 * The chat route (src/app/api/chat/route.ts) serves reginald.md content up to the
 * "## Mode-Specific Behaviors" heading, so the generated block is inserted immediately
 * BEFORE that heading, delimited by PLAYBOOK:BEGIN/END markers. Everything outside the
 * markers is hand-maintained; everything inside is overwritten on every run.
 *
 * Deterministic + idempotent: same playbook in → byte-identical block out
 * (no timestamps). Run after any playbook edit:
 *   npx tsx scripts/playbook/build-chat-prompt.ts
 */
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import matter from 'gray-matter';

const ROOT = process.cwd();
const PLAYBOOK_DIR = path.join(ROOT, 'content', 'playbook');
const PROMPT_PATH = path.join(ROOT, 'src', 'prompts', 'reginald.md');
const BEGIN = '<!-- PLAYBOOK:BEGIN (generated by scripts/playbook/build-chat-prompt.ts — do not edit by hand) -->';
const END = '<!-- PLAYBOOK:END -->';
const MODE_HEADING = '## Mode-Specific Behaviors';

interface Fact {
  id: string;
  statement: string;
  status: 'verified' | 'conflicting' | 'unknown';
  internal_only?: boolean;
  open_question?: string;
}

interface Card {
  id: string;
  tier: 'T1' | 'T2' | 'T3' | 'T4';
  freq_rank: number;
  chat: string | null;
  matchExamples: string[];
}

/** Parse a standalone YAML file using gray-matter (our only declared YAML-capable dep). */
function parseYamlFile(file: string): Record<string, unknown> {
  const raw = fs.readFileSync(file, 'utf8');
  return matter(`---\n${raw}\n---\n`).data as Record<string, unknown>;
}

function loadFacts(): Fact[] {
  const curated = parseYamlFile(path.join(PLAYBOOK_DIR, 'facts.yaml')).facts as Fact[];
  const generated = parseYamlFile(path.join(PLAYBOOK_DIR, 'facts-generated.yaml')).facts as Fact[];
  return [...generated, ...curated];
}

function extractSection(body: string, heading: string): string | null {
  const re = new RegExp(`^## ${heading}\\s*$`, 'm');
  const m = re.exec(body);
  if (!m) return null;
  const start = m.index + m[0].length;
  const rest = body.slice(start);
  const next = rest.search(/^## /m);
  return (next === -1 ? rest : rest.slice(0, next)).trim();
}

function loadCards(): Card[] {
  const dir = path.join(PLAYBOOK_DIR, 'intents');
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => {
      const { data, content } = matter.read(path.join(dir, f));
      return {
        id: data.id as string,
        tier: data.tier as Card['tier'],
        freq_rank: (data.freq_rank as number) ?? 999,
        chat: extractSection(content, 'Chat'),
        matchExamples: ((data.match_examples as string[]) ?? []).slice(0, 2),
      };
    })
    .sort((a, b) => a.freq_rank - b.freq_rank);
}

function extractCompliancePromptBlock(): string {
  const md = fs.readFileSync(path.join(PLAYBOOK_DIR, 'compliance.md'), 'utf8');
  const m = /## Prompt block[^\n]*\n+```\n([\s\S]*?)```/m.exec(md);
  if (!m) throw new Error('compliance.md: fenced "## Prompt block" section not found');
  return m[1].trim();
}

export function buildBlock(): string {
  const facts = loadFacts();
  const cards = loadCards();
  const verified = facts.filter((f) => f.status === 'verified' && !f.internal_only);
  const guarded = facts.filter((f) => f.status !== 'verified');

  const lines: string[] = [];
  lines.push(BEGIN);
  lines.push('');
  lines.push('## Playbook: verified facts (the ONLY facts you may state)');
  lines.push('');
  for (const f of verified) lines.push(`- ${f.statement}`);
  lines.push('');
  lines.push('## Playbook: topics you must NOT assert (unresolved — hedge + hand off)');
  lines.push('');
  lines.push(
    'For these topics, say a human will confirm, and offer the text line (737) 371-9700 — never state a version as fact:'
  );
  for (const f of guarded) lines.push(`- ${f.statement}`);
  lines.push('');
  lines.push('## Playbook: response tiers (these override earlier escalation guidance for service topics)');
  lines.push('');
  lines.push('- T1 answer directly using verified facts only.');
  lines.push('- T2 answer, then for day-of items point to texting (737) 371-9700 as the fastest channel.');
  lines.push(
    '- T3 give general verified info only, then collect a phone number or email so Allan can follow up personally. Never commit to prices, changes, or exceptions.'
  );
  lines.push(
    '- T4 acknowledge only + urgent handoff (refunds, cancellations, complaints, legal, anything about minors or intoxication, day-of failures). Pattern: "I\'m getting Allan right now — drop your number and he\'ll contact you personally today." Never answer the substance.'
  );
  lines.push(
    '- You are the Party On Delivery assistant — never claim to be Allan. (737) 371-9700 is the only phone number you may ever give out.'
  );
  lines.push('');
  lines.push('## Playbook: intent responses (match the customer to one of these; tier drives behavior)');
  lines.push('');
  for (const c of cards) {
    if (!c.chat) continue;
    const example = c.matchExamples[0] ? ` e.g. "${c.matchExamples[0]}"` : '';
    lines.push(`### ${c.id} [${c.tier}]${example}`);
    lines.push(c.chat);
    lines.push('');
  }
  lines.push('## Playbook: compliance (non-negotiable)');
  lines.push('');
  lines.push(extractCompliancePromptBlock());
  lines.push('');
  lines.push(END);
  return lines.join('\n');
}

function main() {
  const block = buildBlock();
  let prompt = fs.readFileSync(PROMPT_PATH, 'utf8');

  const beginIdx = prompt.indexOf(BEGIN);
  const endIdx = prompt.indexOf(END);

  if (beginIdx !== -1 && endIdx !== -1) {
    prompt = prompt.slice(0, beginIdx) + block + prompt.slice(endIdx + END.length);
  } else if (beginIdx === -1 && endIdx === -1) {
    const modeIdx = prompt.indexOf(MODE_HEADING);
    if (modeIdx === -1) {
      throw new Error(`reginald.md: neither markers nor "${MODE_HEADING}" found — refusing to guess`);
    }
    prompt = prompt.slice(0, modeIdx) + block + '\n\n' + prompt.slice(modeIdx);
  } else {
    throw new Error('reginald.md: found one marker but not the other — fix the file by hand');
  }

  fs.writeFileSync(PROMPT_PATH, prompt);
  const blockLines = block.split('\n').length;
  console.log(`reginald.md updated — playbook block: ${blockLines} lines, ${block.length} chars`);
}

// Run only when invoked as a script (vitest imports buildBlock without side effects).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
