/**
 * Datacenter-IP detection for bot classification.
 *
 * Stealth scrapers wear real-browser user-agents, so BOT_UA_REGEX can't see
 * them — but they overwhelmingly run on cloud infrastructure. A request whose
 * client IP falls inside a published cloud range is flagged `is_datacenter` at
 * ingest (see the vercel-drain webhook) and counted as bot traffic by the
 * queries in vercel-events.ts.
 *
 * The ranges are vendored in datacenter-ranges.json (AWS, GCP, Azure,
 * DigitalOcean, Oracle, Linode, Vultr — official sources, pre-merged), and
 * regenerated by scripts/analytics/update-datacenter-ranges.mjs, which keeps
 * its own copy of this IP parsing (it must run on plain node, no TS). Known
 * blind spots: Hetzner/OVH publish no stable feed, and residential proxies are
 * structurally invisible to this approach — so "human" remains a ceiling.
 */

import ranges from './datacenter-ranges.json';

/** [startUint32, endUint32] pairs, sorted; v6 uses fixed-width 32-char hex. */
const V4: [number, number][] = ranges.v4 as [number, number][];
const V6: [string, string][] = ranges.v6 as [string, string][];

function v4ToInt(ip: string): number | null {
  const parts = ip.split('.');
  if (parts.length !== 4) return null;
  let n = 0;
  for (const p of parts) {
    if (!/^\d{1,3}$/.test(p)) return null;
    const b = Number(p);
    if (b > 255) return null;
    n = n * 256 + b;
  }
  return n;
}

/** Normalize any legal IPv6 text form to fixed-width 32-char lowercase hex. */
function v6ToHex(ip: string): string | null {
  let head = ip;
  const v4Tail = ip.match(/:(\d+\.\d+\.\d+\.\d+)$/);
  if (v4Tail) {
    const n = v4ToInt(v4Tail[1]);
    if (n === null) return null;
    head =
      ip.slice(0, -v4Tail[1].length) +
      // eslint-disable-next-line no-bitwise
      ((n >>> 16).toString(16) + ':' + (n & 0xffff).toString(16));
  }
  const dbl = head.split('::');
  if (dbl.length > 2) return null;
  const left = dbl[0] ? dbl[0].split(':') : [];
  const right = dbl.length === 2 && dbl[1] ? dbl[1].split(':') : [];
  const fill = dbl.length === 2 ? 8 - left.length - right.length : 0;
  if (dbl.length === 1 && left.length !== 8) return null;
  if (fill < 0) return null;
  const hextets = [...left, ...Array(fill).fill('0'), ...right];
  if (hextets.length !== 8) return null;
  let out = '';
  for (const h of hextets) {
    if (!/^[0-9a-fA-F]{1,4}$/.test(h)) return null;
    out += h.toLowerCase().padStart(4, '0');
  }
  return out;
}

/** Binary search over sorted, non-overlapping [start, end] ranges. */
function inRanges<T extends number | string>(value: T, sorted: [T, T][]): boolean {
  let lo = 0;
  let hi = sorted.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const [start, end] = sorted[mid];
    if (value < start) hi = mid - 1;
    else if (value > end) lo = mid + 1;
    else return true;
  }
  return false;
}

/**
 * Whether a client IP belongs to a known cloud/datacenter range.
 *
 * Unknown, missing, or malformed input is NOT datacenter — this flag only ever
 * moves traffic from "human" to "bot", so uncertainty stays on the human side
 * rather than inventing bots.
 *
 * @param ip Client IP as received from the drain (v4, v6, or v4-mapped v6).
 */
export function isDatacenterIp(ip?: string | null): boolean {
  if (!ip) return false;
  const trimmed = ip.trim();
  if (trimmed.includes(':')) {
    // v4-mapped v6 (::ffff:1.2.3.4) is really a v4 address — match it there.
    const mapped = trimmed.match(/^::ffff:(\d+\.\d+\.\d+\.\d+)$/i);
    if (mapped) {
      const n = v4ToInt(mapped[1]);
      return n === null ? false : inRanges(n, V4);
    }
    const hex = v6ToHex(trimmed);
    return hex === null ? false : inRanges(hex, V6);
  }
  const n = v4ToInt(trimmed);
  return n === null ? false : inRanges(n, V4);
}
