import fs from 'fs';
const rows: Array<{slug:string, target:string, impr:number, status:string, is_copy_dup:boolean}> =
  JSON.parse(fs.readFileSync('/tmp/redirect-map.json', 'utf8'));

// Group by target for readability
const byTarget = new Map<string, typeof rows>();
for (const r of rows) {
  const arr = byTarget.get(r.target) || [];
  arr.push(r);
  byTarget.set(r.target, arr);
}

const out: string[] = [];
out.push('/**');
out.push(' * Archived + orphaned product URL redirects (sweep 2026-06-10).');
out.push(' *');
out.push(' * Generated by scripts/seo/_build-archived-redirects.mts after the');
out.push(' * 2026-06 GSC + DB audit found that 325 of 535 indexed /products/');
out.push(' * URLs (61%) were ARCHIVED or NOT_IN_DB — leaking ~19,000 impressions');
out.push(' * per 60 days and contributing to the May 2026 Core Update slide as');
out.push(' * an "unhelpful content" signal.');
out.push(' *');
out.push(' * Each entry redirects an old /products/<slug> URL to the closest');
out.push(' * category page based on slug + Product.tags classification. Pages');
out.push(' * with real click demand are flagged in');
out.push(' * docs/seo/recommendations/product-page-editorial-sprint-2026-06.md');
out.push(' * for operator review.');
out.push(' *');
out.push(' * Total: ' + rows.length + ' redirects, ' + rows.reduce((s,r)=>s+r.impr,0).toLocaleString() + ' impressions consolidated.');
out.push(' */');
out.push('');
out.push('export interface ArchivedProductRedirect {');
out.push('  source: string;');
out.push('  destination: string;');
out.push('  permanent: true;');
out.push('}');
out.push('');
out.push('export const ARCHIVED_PRODUCT_REDIRECTS: ArchivedProductRedirect[] = [');

// Sort targets for stable diffs: alphabetical by destination, then by impr desc within each group
const sortedTargets = [...byTarget.keys()].sort();
for (const tgt of sortedTargets) {
  const arr = byTarget.get(tgt)!;
  arr.sort((a, b) => b.impr - a.impr);
  out.push(`  // → ${tgt}  (${arr.length} entries, ${arr.reduce((s,r)=>s+r.impr,0).toLocaleString()} impr)`);
  for (const r of arr) {
    const copyNote = r.is_copy_dup ? ' // -copy migration artifact' : '';
    out.push(`  { source: '/products/${r.slug}', destination: '${tgt}', permanent: true },${copyNote}`);
  }
  out.push('');
}
out.push('];');

fs.writeFileSync('src/lib/seo/archived-product-redirects.ts', out.join('\n') + '\n');
console.log('Wrote src/lib/seo/archived-product-redirects.ts');
console.log('Entries:', rows.length);
